dbt-proj:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: postgres
      pass: postgres
      port: 5432
      dbname: postgres
      schema: public
      threads: 1
